# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 16:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zeet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=140)),
                ('created', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='%Y/%m/%d/images/')),
                ('users_likes', models.ManyToManyField(blank=True, related_name='images_liked', to=settings.AUTH_USER_MODEL)),
                ('zeeter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zeets_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
