# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 07:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zeets', '0002_auto_20170705_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(help_text='350 characters only', max_length=350)),
                ('photo', models.ImageField(blank=True, upload_to='%Y/%m/%d/comments/')),
                ('created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='zeet',
            name='body',
            field=models.CharField(help_text='140 characters only :P', max_length=140),
        ),
        migrations.AddField(
            model_name='comment',
            name='zeet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='zeets.Zeet'),
        ),
    ]
