# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 07:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zeets', '0004_auto_20170706_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='zeet',
            name='users_likes',
        ),
        migrations.AddField(
            model_name='like',
            name='zeet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zeet_liked', to='zeets.Zeet'),
        ),
    ]
