# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 07:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zeets', '0006_auto_20170707_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='zeet',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='zeets_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
