# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 07:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zeets', '0007_zeet_users_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeet',
            name='users_like',
            field=models.ManyToManyField(blank=True, default=0, related_name='zeets_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
